'use client'

import {
	QueryClient,
	QueryClientProvider
} from "@tanstack/react-query";
import "./globals.css";

// export const metadata: Metadata = {
// 	title: "Weather",
// 	description: "Generated by create next app",
// };

// query
const queryClient = new QueryClient();

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
	return (
		<html lang="en">
			<QueryClientProvider client={queryClient}>
				<body>
					{children}
				</body>
			</QueryClientProvider>
		</html>
	);
}
